export const MESSAGE_GAME_LOG = 'SERVER/MESSAGE_GAME_LOG';
export const MESSAGE_CHAT = 'SERVER/MESSAGE_CHAT';
export const MESSAGE_GAME_ACTION = 'SERVER/MESSAGE_GAME_ACTION';
export const MESSAGE_READY = 'SERVER/MESSAGE_READY';
export const MESSAGE_ROLL_DICE = 'SERVER/MESSAGE_ROLL_DICE';
export const MESSAGE_FINISH_TURN = 'SERVER/MESSAGE_FINISH_TURN';
export const MESSAGE_PLACE_STRUCTURE = 'SERVER/MESSAGE_PLACE_STRUCTURE';
export const MESSAGE_PLACE_ROAD = 'SERVER/MESSAGE_PLACE_ROAD';
export const MESSAGE_REMOVE_ROAD = 'SERVER/MESSAGE_REMOVE_ROAD';
export const MESSAGE_PURCHASE_GAME_CARD = 'SERVER/MESSAGE_PURCHASE_GAME_CARD';
export const MESSAGE_PLAY_GAME_CARD = 'SERVER/MESSAGE_PLAY_GAME_CARD';
export const MESSAGE_SELECT_MONOPOLY_RESOURCE = 'SERVER/MESSAGE_SELECT_MONOPOLY_RESOURCE';
export const MESSAGE_COLLECT_ALL_LOOT = 'SERVER/MESSAGE_COLLECT_ALL_LOOT';
export const MESSAGE_DISCARD_HALF_DECK = 'SERVER/MESSAGE_DISCARD_HALF_DECK';
export const MESSAGE_MOVE_ROBBER = 'SERVER/MESSAGE_MOVE_ROBBER';
export const MESSAGE_STEAL_CARD = 'SERVER/MESSAGE_STEAL_CARD';
export const MESSAGE_GAME_VICTORY = 'SERVER/MESSAGE_GAME_VICTORY';

export const MESSAGE_TRADE_WITH_BANK = 'SERVER/MESSAGE_TRADE_WITH_BANK';
export const MESSAGE_TRADE_REQUEST = 'SERVER/MESSAGE_TRADE_REQUEST';
export const MESSAGE_TRADE_ADD_CARD = 'SERVER/MESSAGE_TRADE_ADD_CARD';
export const MESSAGE_TRADE_REMOVE_CARD = 'SERVER/MESSAGE_TRADE_REMOVE_CARD';
export const MESSAGE_TRADE_CONFIRM = 'SERVER/MESSAGE_TRADE_CONFIRM';
export const MESSAGE_TRADE_REFUSE = 'SERVER/MESSAGE_TRADE_REFUSE';
export const MESSAGE_TRADE_START_AGREED = 'SERVER/MESSAGE_TRADE_START_AGREED';

export const MESSAGE_PLACE_GUARD = 'SERVER/MESSAGE_PLACE_GUARD';
export const MESSAGE_REMOVE_GUARD = 'SERVER/MESSAGE_REMOVE_GUARD';
export const MESSAGE_WILDLINGS_REVEAL_TOKENS = 'SERVER/MESSAGE_WILDLINGS_REVEAL_TOKENS';
export const MESSAGE_WILDLINGS_ADVANCE_CLEARING = 'SERVER/MESSAGE_WILDLINGS_ADVANCE_CLEARING';
export const MESSAGE_WILDLINGS_WALL_BATTLE = 'SERVER/MESSAGE_WILDLINGS_WALL_BATTLE';
export const MESSAGE_WILDLINGS_REMOVE_FROM_TILE = 'SERVER/MESSAGE_WILDLINGS_REMOVE_FROM_TILE';

export const MESSAGE_PLAY_HERO_CARD = 'SERVER/MESSAGE_PLAY_HERO_CARD';
export const MESSAGE_SELECT_HERO_CARD = 'SERVER/MESSAGE_SELECT_HERO_CARD';

