export const MESSAGE_GAME_LOG = 'SERVER/MESSAGE_GAME_LOG';
export const MESSAGE_CHAT = 'SERVER/MESSAGE_CHAT';
export const MESSAGE_GAME_ACTION = 'SERVER/MESSAGE_GAME_ACTION';
export const MESSAGE_READY = 'SERVER/MESSAGE_READY';
export const MESSAGE_ROLL_DICE = 'SERVER/MESSAGE_ROLL_DICE';
export const MESSAGE_FINISH_TURN = 'SERVER/MESSAGE_FINISH_TURN';
export const MESSAGE_PLACE_STRUCTURE = 'SERVER/MESSAGE_PLACE_STRUCTURE';
export const MESSAGE_PLACE_ROAD = 'SERVER/MESSAGE_PLACE_ROAD';
