import { TILE_RESOURCE, TILE_WATER, TILE_SPACER } from '../../manifest';

// 7 x 7 === Total of 49 tiles
export default [
  [
    TILE_SPACER,
    TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER,
    TILE_SPACER, TILE_SPACER
  ],
  [
    TILE_SPACER,
    TILE_WATER,
    TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE,
    TILE_WATER,
    TILE_SPACER
  ],
  [
    TILE_WATER,
    TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE,
    TILE_WATER,
    TILE_SPACER
  ]
  ,[
    TILE_WATER,
    TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE,
    TILE_WATER
  ],
  [
    TILE_WATER,
    TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE,
    TILE_WATER,
    TILE_SPACER
  ],
  [
    TILE_SPACER,
    TILE_WATER,
    TILE_RESOURCE, TILE_RESOURCE, TILE_RESOURCE,
    TILE_WATER,
    TILE_SPACER
  ],
  [
    TILE_SPACER,
    TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER,
    TILE_SPACER, TILE_SPACER
  ]
];
